### ISSUE TITLE
Move the release process documentation into a `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by msto** [fulcrumgenomics/prymer#45]
https://github.com/fulcrumgenomics/prymer/wiki/Performing-a-Release

Per Clint (with whom I agree here): 
> SOP in the repo wiki (I'd rather we move it to CONTRIBUTING.md at some point so it is more discoverable and kept in lock-step with the repo)

**Comment by clintval** [comment]
Hey @msto, #32 is merged now.

The main README links to the developer's instructions.

In the developer's instructions, the release process is described.

It is organized this way so that the release process can be rendered with mkdocs easily. If I went with a CONTRIBUTING.md I'm not sure how I'd easily stitch that into the rendered documentation.

Do you think this issue can be closed for now?

At least we solved moving the process from the GitHub repo wiki (hard to find) to the repo itself.

**Comment by msto** [comment]
Fine by me!
